package-lock.json, package.json, src/routes/+layout.svelte, src/routes/+layout.ts, svelte.config.js
=> build: :building_construction: use adapter-static instead of adapter-auto

inject-theme-colors.js, src/lib/styles.scss, src/routes/calendar/full-calendar.css
use blue for links in light mode (closes #38)
make blue more vibrant
use better colors for calendar
=> improve theme colors

package-lock.json, package.json, src/lib/Navbar.svelte
=> feat: 📱 add alternate layout for navigation menu on small screens

.vscode/settings.json, src/routes/about/+page.svelte
Fix spelling issue, improve conciseness, give up-to-date name of Seishinkan Kendo Club in content, add Seishinkan to workspace spell check
=> replace outdated info and improve writing on about us page

src/routes/calendar/+page.svelte, src/routes/calendar/full-calendar.css, src/routes/calendar/full-calendar.ts
=> fix calendar sizing on narrow and wide devices

src/lib/Navbar.svelte
=> add animation when opening and closing the menu on mobile

.vscode/settings.json, package-lock.json, package.json, src/lib/EventInfo.svelte, src/lib/FullCalendar.svelte, src/lib/Navbar.svelte, src/lib/full-calendar-shadow.css, src/lib/styles.scss, src/lib/tippy-theme.css
- add popovers to calendar events with event details
- make contents of popover easily editable by future developers
- make shadow on nav bar only appear in light mode
- make nav bar only transparent with shadow when page is scrolled
- make popover look like nav bar
=> Calendar detail and elevation styling

src/lib/full-calendar-shadow.css
=> fix iOS text color

src/routes/+page.svelte
Removed member dues dollar amount to make website more maintainable. Decreased dues section to a single sentence while still including all important information. This makes it more concise and clear.
Closes #93 
The line above will automatically close that issue (which is kind of like a task in this project) once this pull request is merged. I will merge the pull request after both of you have reviewed it and I've made any changes based on your feedback.
=> Remove member dues dollar amount and make dues section more concise

src/lib/EventInfo.svelte, src/lib/Navbar.svelte, src/lib/SvgIcon.svelte, src/lib/mime-types.ts
I'm using icons, labels, and/or font size to distinguish between the title, time, location, description, etc.
=> Distinguish between sections in calendar event details

src/routes/about/+page.svelte
See commits for details! Ask me if this doesn't make sense
=> Improve about us page tone, conciseness, and punctuation

src/routes/+page.svelte
See comments for details (sorry, I should've made small commits with detailed commit messages, I forgot)
=> improve home page conciseness and clarity

src/routes/+error.svelte
- Include error message in h1
- Add primary color to status code
- Put status code and error message on the same line
- Center horizontally and put slightly above center vertically
Closes #136
=> Add custom error page

src/app.html
Use pico-background-color to set the theme-color
Closes #67
=> Add theme-color

.prettierrc, .prettierrc.js, eslint.config.js, svelte.config.js
This PR makes a few config files more readable and consistent
=> Config refactor

src/lib/FullCalendar.svelte, src/lib/styles.scss
- Make "add to google calendar" and "add to other calendar" buttons
- Create dialog for add to other calendar button with a copy button for the iCal url
=> Create add to calendar button

src/lib/index.ts
This files was part of the empty sveltekit app but we never deleted it.
=> Remove index file from lib

src/routes/(home)/+page.svelte
- Remove explicit costs of shinai and reword the section for better instructions on how to borrow/get a shinai
- Make the caption under a photo less redundant
=> Make changes suggested at the stakeholder meeting on 7/27

src/lib/tippy-theme.css
=> fix: 🐛 make tippy color match pico theme

.vscode/settings.json, eslint.config.js, src/lib/EventInfo.svelte, src/lib/FullCalendar.svelte, src/lib/Navbar.svelte, src/lib/mime-types.ts, vite.config.ts
In this PR I configure eslint to catch more types of programming mistakes
=> stricter eslint rules

src/lib/FullCalendar.svelte
I have no idea why this works lol
=> fix: 🐛 fix add to Google Calendar on Android

src/lib/MetaTags.svelte
=> feat: ✨ make link preview use large image for twitter and discord

package-lock.json, package.json, src/lib/EventInfo.svelte, src/lib/FullCalendar.svelte, src/lib/MetaTags.svelte, src/lib/Modal.svelte, src/lib/Navbar.svelte, src/lib/SvgIcon.svelte, src/routes/+error.svelte, src/routes/+layout.svelte, src/routes/calendar/+page.svelte, src/routes/resources/kendo-beginner-guide/+page.svelte, src/routes/resources/kendo-japanese-pronunciations-and-definitions/+page.svelte
=> Migrate to Svelte 5

src/lib/EventInfo.svelte, src/lib/Navbar.svelte
=> Add keys for each blocks
